# coding: utf-8

"""
    Bitcoind

    The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.  # noqa: E501

    OpenAPI spec version: 0.16
    Contact: johan@lepetitbloc.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.memory_pool_api import MemoryPoolApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMemoryPoolApi(unittest.TestCase):
    """MemoryPoolApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.memory_pool_api.MemoryPoolApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_getutxos(self):
        """Test case for rest_getutxos

        Returns Unspent Transaction (TX) Outputs  # noqa: E501
        """
        pass

    def test_rest_headers(self):
        """Test case for rest_headers

        Returns headers.  # noqa: E501
        """
        pass

    def test_rest_mempool_contents(self):
        """Test case for rest_mempool_contents

        Returns transactions in the TX mempool.  # noqa: E501
        """
        pass

    def test_rest_mempool_info(self):
        """Test case for rest_mempool_info

        Returns various information about the TX mempool.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
