# coding: utf-8

"""
    Bitcoind

    The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.  # noqa: E501

    OpenAPI spec version: 0.16
    Contact: johan@lepetitbloc.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_api import TransactionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionApi(unittest.TestCase):
    """TransactionApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transaction_api.TransactionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rest_tx(self):
        """Test case for rest_tx

        Get transaction by hash.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
