# coding: utf-8

"""
    Bitcoind

    The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.  # noqa: E501

    OpenAPI spec version: 0.16
    Contact: johan@lepetitbloc.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.bip_reject import BIPReject  # noqa: F401,E501


class BIP(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'version': 'int',
        'reject': 'BIPReject'
    }

    attribute_map = {
        'id': 'id',
        'version': 'version',
        'reject': 'reject'
    }

    def __init__(self, id=None, version=None, reject=None):  # noqa: E501
        """BIP - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._version = None
        self._reject = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if version is not None:
            self.version = version
        if reject is not None:
            self.reject = reject

    @property
    def id(self):
        """Gets the id of this BIP.  # noqa: E501

        The BIP number, or ? before being assigned  # noqa: E501

        :return: The id of this BIP.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BIP.

        The BIP number, or ? before being assigned  # noqa: E501

        :param id: The id of this BIP.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this BIP.  # noqa: E501

        The BIP version number  # noqa: E501

        :return: The version of this BIP.  # noqa: E501
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this BIP.

        The BIP version number  # noqa: E501

        :param version: The version of this BIP.  # noqa: E501
        :type: int
        """

        self._version = version

    @property
    def reject(self):
        """Gets the reject of this BIP.  # noqa: E501


        :return: The reject of this BIP.  # noqa: E501
        :rtype: BIPReject
        """
        return self._reject

    @reject.setter
    def reject(self, reject):
        """Sets the reject of this BIP.


        :param reject: The reject of this BIP.  # noqa: E501
        :type: BIPReject
        """

        self._reject = reject

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BIP):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
