# coding: utf-8

"""
    Bitcoind

    The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.  # noqa: E501

    OpenAPI spec version: 0.16
    Contact: johan@lepetitbloc.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.u_tx_o import UTxO  # noqa: F401,E501


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'chain_height': 'int',
        'chaintip_hash': 'str',
        'bitmap': 'str',
        'utxos': 'list[UTxO]'
    }

    attribute_map = {
        'chain_height': 'chainHeight',
        'chaintip_hash': 'chaintipHash',
        'bitmap': 'bitmap',
        'utxos': 'utxos'
    }

    def __init__(self, chain_height=None, chaintip_hash=None, bitmap=None, utxos=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._chain_height = None
        self._chaintip_hash = None
        self._bitmap = None
        self._utxos = None
        self.discriminator = None

        if chain_height is not None:
            self.chain_height = chain_height
        if chaintip_hash is not None:
            self.chaintip_hash = chaintip_hash
        if bitmap is not None:
            self.bitmap = bitmap
        if utxos is not None:
            self.utxos = utxos

    @property
    def chain_height(self):
        """Gets the chain_height of this InlineResponse200.  # noqa: E501


        :return: The chain_height of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._chain_height

    @chain_height.setter
    def chain_height(self, chain_height):
        """Sets the chain_height of this InlineResponse200.


        :param chain_height: The chain_height of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._chain_height = chain_height

    @property
    def chaintip_hash(self):
        """Gets the chaintip_hash of this InlineResponse200.  # noqa: E501


        :return: The chaintip_hash of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._chaintip_hash

    @chaintip_hash.setter
    def chaintip_hash(self, chaintip_hash):
        """Sets the chaintip_hash of this InlineResponse200.


        :param chaintip_hash: The chaintip_hash of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._chaintip_hash = chaintip_hash

    @property
    def bitmap(self):
        """Gets the bitmap of this InlineResponse200.  # noqa: E501


        :return: The bitmap of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._bitmap

    @bitmap.setter
    def bitmap(self, bitmap):
        """Sets the bitmap of this InlineResponse200.


        :param bitmap: The bitmap of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._bitmap = bitmap

    @property
    def utxos(self):
        """Gets the utxos of this InlineResponse200.  # noqa: E501


        :return: The utxos of this InlineResponse200.  # noqa: E501
        :rtype: list[UTxO]
        """
        return self._utxos

    @utxos.setter
    def utxos(self, utxos):
        """Sets the utxos of this InlineResponse200.


        :param utxos: The utxos of this InlineResponse200.  # noqa: E501
        :type: list[UTxO]
        """

        self._utxos = utxos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
