# coding: utf-8

"""
    Bitcoind

    The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.  # noqa: E501

    OpenAPI spec version: 0.16
    Contact: johan@lepetitbloc.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.script_pub_key import ScriptPubKey  # noqa: F401,E501


class UTxO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'txvers': 'int',
        'height': 'int',
        'value': 'float',
        'script_pub_key': 'ScriptPubKey'
    }

    attribute_map = {
        'txvers': 'txvers',
        'height': 'height',
        'value': 'value',
        'script_pub_key': 'scriptPubKey'
    }

    def __init__(self, txvers=None, height=None, value=None, script_pub_key=None):  # noqa: E501
        """UTxO - a model defined in Swagger"""  # noqa: E501

        self._txvers = None
        self._height = None
        self._value = None
        self._script_pub_key = None
        self.discriminator = None

        if txvers is not None:
            self.txvers = txvers
        if height is not None:
            self.height = height
        if value is not None:
            self.value = value
        if script_pub_key is not None:
            self.script_pub_key = script_pub_key

    @property
    def txvers(self):
        """Gets the txvers of this UTxO.  # noqa: E501


        :return: The txvers of this UTxO.  # noqa: E501
        :rtype: int
        """
        return self._txvers

    @txvers.setter
    def txvers(self, txvers):
        """Sets the txvers of this UTxO.


        :param txvers: The txvers of this UTxO.  # noqa: E501
        :type: int
        """

        self._txvers = txvers

    @property
    def height(self):
        """Gets the height of this UTxO.  # noqa: E501


        :return: The height of this UTxO.  # noqa: E501
        :rtype: int
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this UTxO.


        :param height: The height of this UTxO.  # noqa: E501
        :type: int
        """

        self._height = height

    @property
    def value(self):
        """Gets the value of this UTxO.  # noqa: E501


        :return: The value of this UTxO.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this UTxO.


        :param value: The value of this UTxO.  # noqa: E501
        :type: float
        """

        self._value = value

    @property
    def script_pub_key(self):
        """Gets the script_pub_key of this UTxO.  # noqa: E501


        :return: The script_pub_key of this UTxO.  # noqa: E501
        :rtype: ScriptPubKey
        """
        return self._script_pub_key

    @script_pub_key.setter
    def script_pub_key(self, script_pub_key):
        """Sets the script_pub_key of this UTxO.


        :param script_pub_key: The script_pub_key of this UTxO.  # noqa: E501
        :type: ScriptPubKey
        """

        self._script_pub_key = script_pub_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UTxO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
